<?php

if (!defined('ABSPATH')) {
	exit; // Exit if accessed directly
}

class OBF_Scripts {

	public function enqueue() {
		$build_dir = plugin_dir_path(dirname(__FILE__)) . 'build/';
		$build_url = plugin_dir_url(dirname(__FILE__)) . 'build/';

		// Only run get_current_screen() if we're in the admin
		if (is_admin()) {
			$current_screen = get_current_screen();

			// Check if we're on the specific admin page for the plugin
			if (isset($current_screen->base) && $current_screen->base === 'toplevel_page_obf-pws-badges') {
				$js_files = glob($build_dir . 'assets/*.js');
				$css_files = glob($build_dir . 'assets/*.css');

				// Enqueue all JS files generated by the build process
				foreach ($js_files as $js_file) {
					$js_file_url = $build_url . 'assets/' . basename($js_file);
					wp_enqueue_script('obf-vue-js', $js_file_url, ['wp-blocks', 'wp-i18n', 'wp-element', 'wp-block-editor', 'wp-components', 'wp-api-fetch'], '1.0.0', true);
				}

				// Enqueue all CSS files generated by the build process
				foreach ($css_files as $css_file) {
					$css_file_url = $build_url . 'assets/' . basename($css_file);
					wp_enqueue_style('obf-vue-css', $css_file_url, [], '1.0.0');
				}

				// Localize script for nonces and other dynamic data
				wp_localize_script('obf-vue-js', 'obfOptions', [
					'ajaxurl' => admin_url('admin-ajax.php'),
					'nonce' => wp_create_nonce('wp_rest'),
				]);
			}
		}

		// Enqueue assets for both the admin editor and the front-end view
		$block_js_file = glob($build_dir . 'assets/badges-block*.js');
		$main_css_file = glob($build_dir . 'assets/main*.css');

		// Enqueue the block's JavaScript on both front-end and editor
		if (!empty($block_js_file)) {
			error_log( 'not empty' );
			wp_enqueue_script(
				'obf-badges-block',
				$build_url . 'assets/' . basename($block_js_file[0]),
				['wp-blocks', 'wp-element', 'wp-i18n', 'wp-components', 'wp-api-fetch'], // Ensure dependencies are met
				filemtime($block_js_file[0]),
				true
			);
			// Set the script to type="module"
			wp_script_add_data('obf-badges-block', 'type', 'module');

			// Localize script for nonces and other dynamic data
			wp_localize_script('obf-badges-block', 'obfOptions', [
				'ajaxurl' => admin_url('admin-ajax.php'),
				'nonce' => wp_create_nonce('wp_rest'),
			]);
		}

		// Enqueue the block's CSS on both front-end and editor
		if (!empty($main_css_file)) {
			wp_enqueue_style(
				'obf-badges-block-styles',
				$build_url . 'assets/' . basename($main_css_file[0]),
				[],
				filemtime($main_css_file[0])
			);
		}
	}
}
