<?php

if (!defined('ABSPATH')) {
	exit; // Exit if accessed directly
}

class OBF_Scripts {

	public function enqueue() {
		$build_dir = plugin_dir_path(dirname(__FILE__)) . 'build/';
		$build_url = plugin_dir_url(dirname(__FILE__)) . 'build/';

		// Enqueue assets specifically for the admin area
		if (is_admin()) {

			$current_screen = get_current_screen();

			// Check if we're on the specific admin page for the plugin
			if (isset($current_screen->base) && $current_screen->base === 'toplevel_page_obf-pws-badges') {
				$js_files = glob($build_dir . 'assets/main*.js');

				$count = 1;
				foreach ($js_files as $js_file) {
					$js_file_url = $build_url . 'assets/' . basename($js_file);
					wp_enqueue_script('obf-vue-main-js-' . $count, $js_file_url, [
						'wp-blocks',
						'wp-i18n',
						'wp-element',
						'wp-block-editor',
						'wp-components',
						'wp-api-fetch'
					], filemtime($js_file), true); // Use file modification time for versioning
					$count++;
				}
			} else {
				$js_files = glob($build_dir . 'assets/badges-block*.js');

				$count = 1;
				foreach ($js_files as $js_file) {
					$js_file_url = $build_url . 'assets/' . basename($js_file);
					wp_enqueue_script('obf-vue-badge-blocks-js-' . $count, $js_file_url, [
						'wp-blocks',
						'wp-i18n',
						'wp-element',
						'wp-block-editor',
						'wp-components',
						'wp-api-fetch'
					], filemtime($js_file), true); // Use file modification time for versioning
					$count++;
				}
			}
		}

		// Localize the main Vue script if it was enqueued
		if (wp_script_is('obf-vue-main-js-1', 'enqueued')) {
			wp_localize_script('obf-vue-main-js-1', 'obfOptions', [
				'ajaxurl' => admin_url('admin-ajax.php'),
				'nonce'   => wp_create_nonce('wp_rest'),
			]);
		}

		// Localize the badge block script if it was enqueued
		if (wp_script_is('obf-vue-badge-blocks-js-1', 'enqueued')) {
			wp_localize_script('obf-vue-badge-blocks-js-1', 'obfOptions', [
				'ajaxurl' => admin_url('admin-ajax.php'),
				'nonce'   => wp_create_nonce('wp_rest'),
			]);
		}

		$css_files = glob($build_dir . 'assets/*.css');

		// Enqueue all CSS files generated by the build process
		$count = 1;
		foreach ($css_files as $css_file) {
			$css_file_url = $build_url . 'assets/' . basename($css_file);
			wp_enqueue_style('obf-vue-css' . $count, $css_file_url, [], filemtime($css_file)); // Use file modification time for versioning
			$count++;
		}
	}
}